### PR TITLE
try to fix issue #49 from original repository

### PR DESCRIPTION
**Pull request by dotenorio**
I did the [comment suggestion](https://github.com/nuintun/node-adodb/issues/49#issuecomment-369666490) for issue #49. But for my PKG solution i was need to add `adodb.js` to root of my application.

I hope I have helped this beautiful project

### CODE REVIEW

**Comment by nuintun** [comment]
This is not a safe change, if user dir includes 'snapshot' but not in PKG will cause an error.
I will add a setting to configure `adodb.js` path in next version!

**Comment by dotenorio** [comment]
Ok, thanks bro!

Em qui, 31 de mai de 2018 12:40, nuintun <notifications@github.com>
escreveu:

**Comment by chrissantamaria** [comment]
I've been having this same issue, any updates on when the setting will get pushed in the next release?

**Comment by Kgroop** [comment]
HI, how can i fix this error with PKG?

**Comment by dotenorio** [comment]
Try to see this pull request modification.. For me it solved!

It's a not best solution but...

Em qua, 26 de set de 2018 19:31, Kgroop <notifications@github.com> escreveu:

**Pull request closed without merging**
